# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: p770242  # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see below
    name: p770242/MM.SalesTools.Services.CrmService/  # repository name (format depends on `type`)
    ref: refs/heads/master  # ref name to use, defaults to 'refs/heads/master'
    endpoint: NABGithub  # name of the service connection to use (for non-Azure Repos types)

trigger:
- master

pool:
  default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'